function channels = setnet(options)


ppDistance = options.topology(1);
sdDistance = options.topology(2);
sxPosition = options.topology(3);
syPosition = options.topology(4);
% Primary transmitter position
psPos = [ppDistance; 0];
% Primary receiver position
pdPos = [0; 0];
% Secondary sources nodes positions
ssPos = [sxPosition; syPosition];
% Secondary relays nodes positions
srPos = [sxPosition + sdDistance/2; syPosition];
% Set the receivers positions
sdPos = [sxPosition + sdDistance; syPosition];


% Plot net if plot option is set
if (options.show == true)
  % Create a new figure
  figure; axes;
  % Hold cuurent plot
  hold on
  % Plot secondary sources as red circles 
  plot(ssPos(1, :), ssPos(2, :), 'o', 'MarkerFaceColor', 'r');
  % Plot secondary destinations as blue circles 
  plot(sdPos(1, :), sdPos(2, :), 'o', 'MarkerFaceColor', 'b');
  % Plot secondary relays as green squares
  for k = 1:options.nSec
    x = srPos(1, k, :);
    y = srPos(2, k, :);
    plot(x(:), y(:), 's', 'MarkerFaceColor', 'g');
    for n = 1:numel(x)
      text(x(n), y(n), ['   ', num2str(n)] ,'FontSize', 6)
    end   
  end
  axis square
end

beta1 = 10^-5.94;
alpha1 = 3.5;

beta2 = 10^-4.68;
alpha2 = 1.8;

channels = struct(...
    'pp', getchannels( struct(...
      'spos', psPos, ...
      'dpos', pdPos, ...
      'alpha', alpha1, ...
      'beta', beta1  ...
      )), ...
    'sr', getchannels( struct(...
      'spos', ssPos, ...
      'dpos', srPos, ...
      'alpha', alpha2, ...
      'beta', beta2  ...
      )), ...
    'sd', getchannels( struct(...
      'spos', ssPos, ...
      'dpos', sdPos, ...
      'alpha', alpha2, ...
      'beta', beta2  ...
      )), ...
    'sp', getchannels( struct(...
      'spos', ssPos, ...
      'dpos', pdPos, ...
      'alpha', alpha1, ...
      'beta', beta1  ...
      )), ...
    'rd', getchannels( struct(...
      'spos', srPos, ...
      'dpos', sdPos, ...
      'alpha', alpha2, ...
      'beta', beta2  ...
      )), ...
    'rp', getchannels( struct(...
      'spos', srPos, ...
      'dpos', pdPos, ...
      'alpha', alpha1, ...
      'beta', beta1  ...
      )), ...
    'pr', getchannels( struct(...
      'spos', psPos, ...
      'dpos', srPos, ...
      'alpha', alpha1, ...
      'beta', beta1  ...
      )), ...
    'pd', getchannels( struct(...
      'spos', psPos, ...
      'dpos', sdPos, ...
      'alpha', alpha1, ...
      'beta', beta1  ...
      )) ...
    );